### ISSUE TITLE
LATIN SMALL LETTER SHARP S is wrongly mapped to the capital version

### ISSUE THREAD

**Issue by qorron** [Corion/Encode-DIN66003#1]
I ran across this line:
https://github.com/Corion/Encode-DIN66003/blob/ccc9b42403c70fe2c3a72364b80dcd6da19c24f1/ucm/din66003.ucm#L137

U1E9E is the "Latin Capital Letter Sharp S"
https://unicode-table.com/en/1E9E/

correct one is:
https://unicode-table.com/en/00DF/

**Comment by Corion** [comment]
Thanks for reporting this! I've fixed it in the released 0.04 version!

**Comment by qorron** [comment]
actually.. it's DF, not FD.

FD would be LATIN SMALL LETTER Y WITH ACUTE
https://www.fileformat.info/info/unicode/char/00fd/index.htm

**Comment by Corion** [comment]
This is embarrassing, but I've released 0.05 , which fixes that
... but it has the wrong comment in the Changes file and git commit. Oh well ...

Thanks for spotting this!
